name: PR Automation

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  automate-pr:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # Necessari per llegir fitxers del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Executa el script de PR
      - name: Assign author and add Redmine link
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/index.js');
            await script({ github, context });